# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.3
minecraft_version_range=[26.3]
neo_version=26.3.0.23-beta

mod_id=vr
mod_name=Visual Redstone
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=net.neverandy.vr
mod_authors=Naverene
mod_description=Hold the Redstone Visualizer to see which blocks carry a redstone signal.
